"""classes table

Revision ID: 8ace62e425ee
Revises: 
Create Date: 2021-01-14 20:40:40.974641

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8ace62e425ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Student')
    op.drop_table('Grade')
    op.drop_table('Subject')
    op.drop_table('Class')
    op.drop_table('Teacher')
    op.drop_table('Parent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Parent',
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('login', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['Student.student_id'], name='Parent_student_id_fkey'),
    sa.PrimaryKeyConstraint('parent_id', name='Parent_pkey')
    )
    op.create_table('Teacher',
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('mail', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('login', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('teacher_id', name='Teacher_pkey'),
    sa.UniqueConstraint('mail', name='Teacher_mail_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Class',
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('class_id', name='Class_pkey'),
    sa.UniqueConstraint('name', name='Class_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Subject',
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['Class.class_id'], name='Subject_class_id_fkey'),
    sa.ForeignKeyConstraint(['teacher_id'], ['Teacher.teacher_id'], name='Subject_teacher_id_fkey'),
    sa.PrimaryKeyConstraint('subject_id', name='Subject_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Grade',
    sa.Column('grade_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('subject_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('value', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['Student.student_id'], name='Grade_student_id_fkey'),
    sa.ForeignKeyConstraint(['subject_id'], ['Subject.subject_id'], name='Grade_subject_id_fkey'),
    sa.PrimaryKeyConstraint('grade_id', name='Grade_pkey')
    )
    op.create_table('Student',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('surname', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('mail', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('login', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=250), autoincrement=False, nullable=False),
    sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['Class.class_id'], name='class_id'),
    sa.PrimaryKeyConstraint('student_id', name='Student_pkey'),
    sa.UniqueConstraint('mail', name='Student_mail_key')
    )
    # ### end Alembic commands ###
